flags: {}
extra-package-dbs: []
local-bin-path: null
extra-lib-dirs:
- /usr/local/Cellar/libffi/3.0.13/lib
packages:
- '.'
extra-deps:
- base-orphans-0.5.4
- free-4.12.4
- kan-extensions-5.0.1
- lens-4.14
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
- megaparsec-4.2.0
- reflection-2.1.2
- semigroupoids-5.0.1
- vector-0.11.0.0
resolver: lts-3.9
